config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root 'articles#index', as: :authenticated_root
  end

  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :articles, except: [:new, :edit] do
    resources :bookmarks, only: [:create]

    member do
      patch :archive
      patch :favourite
      get :card
      get :card_sm
      patch :update_summary_prompt
      post :regenerate_summary
    end

    collection do
      get :archived
      get :favourites
      get :search
    end
  end

  resources :bookmarks, only: [:create,:destroy]

  resources :summary_prompts, only: [:index, :create, :destroy, :update]

  resources :conversations, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :curations, only: [:index, :show, :create, :destroy, :update]

  get 'tags/:tag', to: 'tags#show', as: :tag

  namespace :api do
    resources :articles, only: [:index, :show]
  end
end

app/views/shared/navbar/_account_links.html.erb
<li><%= link_to "My Account", edit_user_registration_path, class: "dropdown-item" %></li>
<li><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %></li>

app/views/shared/navbar/_desktop.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon d-none d-md-flex">
  <div class="container-fluid">
    <%= render "shared/navbar/logo" %>

    <h2 class="flex-grow-1 text-center m-0">
      <%= link_to "StoryPile", root_path, class: "navbar-title" %>
    </h2>

    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle-no-caret"
            id="desktopMenuDropdown" role="button" data-bs-toggle="dropdown">
          <i class="fa-solid fa-circle-user fa-2xl" style="position: relative; top: 8px;"></i>
        </a>

        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="desktopMenuDropdown">
          <%= render "shared/navbar/nav_links" %>
          <%= render "shared/navbar/account_links" %>
          <%= render "shared/navbar/install_button", id: "install-menu-item-desktop", button_id: "install-button-desktop" %>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/navbar/_install_button.html.erb
<li id="<%= local_assigns[:id] || 'install-menu-item' %>" style="display: none;">
  <button id="<%= local_assigns[:button_id] || 'install-button' %>" class="dropdown-item <%= local_assigns[:align] %>">
    <i class="fa-solid fa-download me-2"></i>Install App
  </button>
</li>

app/views/shared/navbar/_logged_out.html.erb
<nav class="navbar navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= render "shared/navbar/logo" %>
    <%= link_to "Login", new_user_session_path, class: "btn btn-outline-dark ms-auto" %>
  </div>
</nav>

app/views/shared/navbar/_logo.html.erb
<%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "storypilelogo-edit.png", alt: "StoryPile Logo", class: "logo" %>
<% end %>

app/views/shared/navbar/_mobile.html.erb
<nav class="navbar navbar-light navbar-lewagon d-md-none">
  <div class="container-fluid position-relative">
    <%= render "shared/navbar/logo" %>

    <div class="mobile-center-nav text-center">
      <div class="dropdown d-inline-block" data-controller="mobile-dropdown">
        <a href="#"
          class="nav-link dropdown-toggle text-dark fw-semibold text-center px-0"
          id="mobileNavDropdown"
          role="button"
          data-bs-toggle="dropdown"
          aria-expanded="false">
          <span class="fw-semibold"><%= current_section_label %></span>
        </a>
        <ul class="dropdown-menu dropdown-menu-end text-center mobile-nav-dropdown" aria-labelledby="mobileNavDropdown">
          <%= render "shared/navbar/nav_links" %>
        </ul>
      </div>
    </div>

    <div class="dropdown me-3" data-controller="mobile-dropdown">
      <a href="#"
         class="nav-link dropdown-toggle-no-caret text-dark"
         id="mobileAccountDropdown"
         role="button"
         data-bs-toggle="dropdown"
         aria-expanded="false">
          <i class="fa-solid fa-circle-user fa-2xl" style="position: relative; top: 8px;"></i>
      </a>
      <ul class="dropdown-menu dropdown-menu-end text-end mobile-nav-dropdown" aria-labelledby="mobileAccountDropdown">
        <%= render "shared/navbar/account_links" %>
        <%= render "shared/navbar/install_button", id: "install-menu-item", button_id: "install-button-mobile", align: "text-end" %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/navbar/_nav_links.html.erb
<li><%= link_to "My Articles", root_path, class: "dropdown-item" %></li>
<li><%= link_to "Curations", curations_path, class: "dropdown-item" %></li>
<li><%= link_to "Favourites", favourites_articles_path, class: "dropdown-item" %></li>
<li><%= link_to "Archived", archived_articles_path, class: "dropdown-item" %></li>
<li><%= link_to "Summary Prompts", summary_prompts_path, class: "dropdown-item" %></li>